version: "3.8"

services:
  personal-site:
    image: julesverne22/personal-site:latest
    ports:
      - "3030:3000"
    networks:
      - test
    restart: unless-stopped

networks:
  test:
    name: test
    external: true
